/**
 * `jellyclaw serve` — Phase 10.02.
 *
 * Flag parsing is owned by Commander in `main.ts`. This module is the action
 * handler: it resolves the bind host, bearer token, and CORS allowlist, then
 * constructs a RunManager + Hono app via Agent A's factories and blocks on
 * the HTTP server until SIGTERM/SIGINT.
 *
 * This module MUST NOT call `process.exit()` — per CLAUDE.md the only allowed
 * exit-site is `cli/main.ts`. We return a numeric exit code instead.
 */

import { randomBytes } from "node:crypto";
import type { Server as HttpServer } from "node:http";

import type { Hono } from "hono";

import { HookRegistry } from "../hooks/registry.js";
import type { Logger } from "../logger.js";
import { createLogger } from "../logger.js";
import { compilePermissions } from "../permissions/rules.js";
import type { CompiledPermissions } from "../permissions/types.js";
import { AnthropicProvider } from "../providers/anthropic.js";
import type { Provider } from "../providers/types.js";
import type { AppVariables, CorsOrigin, RunManager, ServerConfig } from "../server/types.js";
import { AuthTokenMissingError, BindSafetyError } from "../server/types.js";
import { SessionPaths } from "../session/paths.js";

/** Default model for HTTP-initiated runs. Cheap for smoke tests; per-run
 * overrides via CreateRunOptions.model supersede this. */
const DEFAULT_SERVE_MODEL = "claude-haiku-4-5-20251001";

// ---------------------------------------------------------------------------
// CLI options (after Commander's camelCase normalisation)
// ---------------------------------------------------------------------------

export interface ServeCliOptions {
  readonly port?: string;
  readonly host?: string;
  readonly authToken?: string;
  readonly cors?: string;
  readonly iKnowWhatImDoing?: boolean;
  readonly verbose?: boolean;
}

// ---------------------------------------------------------------------------
// Dependency injection
// ---------------------------------------------------------------------------

export interface ServeActionDeps {
  readonly env: NodeJS.ProcessEnv;
  readonly stdout: NodeJS.WritableStream;
  readonly stderr: NodeJS.WritableStream;
  readonly createRunManager: (args: {
    readonly logger: Logger;
    readonly sessionPaths: SessionPaths;
  }) => RunManager;
  readonly buildApp: (args: {
    readonly config: ServerConfig;
    readonly runManager: RunManager;
    readonly sessionPaths: SessionPaths;
    readonly logger: Logger;
    readonly version: string;
  }) => Hono<{ Variables: AppVariables }> | Promise<Hono<{ Variables: AppVariables }>>;
  readonly startServer: (args: {
    readonly config: ServerConfig;
    readonly app: Hono<{ Variables: AppVariables }>;
    readonly logger: Logger;
    readonly allowNonLoopback?: boolean;
  }) => Promise<{ server: HttpServer; port: number }>;
  readonly parseCorsOrigins: (csv: string) => readonly CorsOrigin[];
  readonly onSignal: (signal: "SIGINT" | "SIGTERM", handler: () => void) => () => void; // returns cleanup
  readonly generateToken: () => string;
  readonly createLogger: typeof createLogger;
  readonly version: string;
}

// ---------------------------------------------------------------------------
// Pure helpers (exported for testing)
// ---------------------------------------------------------------------------

const LOOPBACK_HOSTS = new Set(["127.0.0.1", "::1", "localhost"]);

export function isLoopback(host: string): boolean {
  return LOOPBACK_HOSTS.has(host.toLowerCase());
}

export interface ResolvedTokenResult {
  readonly token: string;
  readonly autoGenerated: boolean;
  readonly source: "flag" | "env:OPENCODE_SERVER_PASSWORD" | "env:JELLYCLAW_TOKEN" | "auto";
}

export function resolveAuthToken(
  flag: string | undefined,
  env: NodeJS.ProcessEnv,
  generateToken: () => string,
): ResolvedTokenResult {
  if (flag !== undefined && flag.length > 0) {
    return { token: flag, autoGenerated: false, source: "flag" };
  }
  const opencodePw = env.OPENCODE_SERVER_PASSWORD;
  if (typeof opencodePw === "string" && opencodePw.length > 0) {
    return { token: opencodePw, autoGenerated: false, source: "env:OPENCODE_SERVER_PASSWORD" };
  }
  const jellyTok = env.JELLYCLAW_TOKEN;
  if (typeof jellyTok === "string" && jellyTok.length > 0) {
    return { token: jellyTok, autoGenerated: false, source: "env:JELLYCLAW_TOKEN" };
  }
  return { token: generateToken(), autoGenerated: true, source: "auto" };
}

export function parsePort(raw: string | undefined): number {
  const s = raw ?? "8765";
  const n = Number.parseInt(s, 10);
  if (Number.isNaN(n) || n <= 0 || n > 65_535) {
    throw new Error(`invalid --port: "${s}" (must be 1..65535)`);
  }
  return n;
}

// ---------------------------------------------------------------------------
// Factory + default action
// ---------------------------------------------------------------------------

function onSignalDefault(signal: "SIGINT" | "SIGTERM", handler: () => void): () => void {
  const wrapped = (): void => handler();
  process.once(signal, wrapped);
  return () => process.removeListener(signal, wrapped);
}

/**
 * Build the action closure from explicit dependencies. Tests pass in spies;
 * the real `serveAction` below wires `buildDefaultDeps()` plus dynamic imports
 * for `parseCorsOrigins` and `createRunManager`.
 */
export function createServeAction(
  deps: ServeActionDeps,
): (options: ServeCliOptions) => Promise<number> {
  return async (options) => {
    const host = options.host ?? "127.0.0.1";
    const port = parsePort(options.port);
    const verbose = options.verbose === true;
    const iKnow = options.iKnowWhatImDoing === true;

    // --- host safety -------------------------------------------------------
    const loopback = isLoopback(host);
    if (!loopback) {
      if (!iKnow) {
        throw new BindSafetyError(
          `refusing to bind to ${host}: non-loopback binds require --i-know-what-im-doing. ` +
            `Loopback (default 127.0.0.1) is safe; binding to a LAN or public interface exposes ` +
            `the HTTP API to other hosts on the network. If you truly intend this, pass ` +
            `--i-know-what-im-doing AND an explicit --auth-token (or OPENCODE_SERVER_PASSWORD env).`,
        );
      }
    }

    // --- auth token --------------------------------------------------------
    const tokenResult = resolveAuthToken(options.authToken, deps.env, deps.generateToken);

    if (!loopback) {
      // Non-loopback bind AND auto-generated token: reject. Auto-gen is only
      // acceptable on loopback because the token never crosses the network.
      if (tokenResult.autoGenerated) {
        throw new AuthTokenMissingError(
          `refusing to bind to ${host} without an explicit auth token. ` +
            `Pass --auth-token <token>, or set OPENCODE_SERVER_PASSWORD / JELLYCLAW_TOKEN in the environment. ` +
            `Auto-generated tokens are only safe on loopback interfaces.`,
        );
      }
      // Loud banner to stderr.
      const banner = buildNonLoopbackBanner(host, port, tokenResult.source, verbose);
      deps.stderr.write(banner);
    }

    // --- auto-gen token disclosure -----------------------------------------
    if (tokenResult.autoGenerated) {
      // Print ONCE to stdout so a parent dispatcher can capture it. Never log
      // via pino (the logger redacts Authorization but not arbitrary tokens
      // in messages; belt + braces — keep it off the structured log).
      deps.stdout.write(`jellyclaw serve: generated bearer token: ${tokenResult.token}\n`);
    }

    // --- CORS --------------------------------------------------------------
    const corsRaw = options.cors ?? "http://localhost:*,http://127.0.0.1:*";
    const corsOrigins = deps.parseCorsOrigins(corsRaw);

    // --- logger + paths ----------------------------------------------------
    const logger = deps.createLogger({
      name: "jellyclaw-serve",
      level: verbose ? "debug" : "info",
    });
    const sessionPaths = new SessionPaths();

    // --- config ------------------------------------------------------------
    const config: ServerConfig = {
      host,
      port,
      authToken: tokenResult.token,
      corsOrigins,
      verbose,
    };

    // --- run manager + app + server ---------------------------------------
    const runManager = deps.createRunManager({ logger, sessionPaths });
    const app = await deps.buildApp({
      config,
      runManager,
      sessionPaths,
      logger,
      version: deps.version,
    });
    const { server } = await deps.startServer({
      config,
      app,
      logger,
      allowNonLoopback: !loopback,
    });

    // NB: we deliberately do not log the token. Logger redaction covers the
    // `authToken` field name via the redact list in `logger.ts`, but we avoid
    // even structuring it into the event in the first place.
    logger.info({ host, port }, `listening on http://${host}:${port}`);

    // --- graceful shutdown -------------------------------------------------
    return await new Promise<number>((resolveExit) => {
      let shuttingDown = false;

      const shutdown = (signal: "SIGINT" | "SIGTERM"): void => {
        if (shuttingDown) return;
        shuttingDown = true;
        logger.info({ signal }, "shutdown signal received");
        const grace = 30_000;
        Promise.resolve(runManager.shutdown(grace))
          .catch((err: unknown) => {
            logger.error({ err }, "runManager.shutdown threw");
          })
          .finally(() => {
            server.close((closeErr) => {
              if (closeErr) {
                logger.error({ err: closeErr }, "server.close error");
                resolveExit(1);
                return;
              }
              resolveExit(0);
            });
          });
      };

      deps.onSignal("SIGINT", () => shutdown("SIGINT"));
      deps.onSignal("SIGTERM", () => shutdown("SIGTERM"));

      // If the server closes on its own (e.g. bind error surfaced
      // asynchronously), resolve so main.ts doesn't hang.
      server.on("close", () => {
        if (!shuttingDown) resolveExit(0);
      });
      server.on("error", (err: Error) => {
        logger.error({ err }, "server error");
        if (!shuttingDown) resolveExit(1);
      });
    });
  };
}

// ---------------------------------------------------------------------------
// Banner
// ---------------------------------------------------------------------------

function buildNonLoopbackBanner(
  host: string,
  port: number,
  tokenSource: ResolvedTokenResult["source"],
  verbose: boolean,
): string {
  const rule = "!!!".repeat(24);
  const lines: string[] = [
    rule,
    `!!! jellyclaw serve: NON-LOOPBACK BIND ENABLED`,
    `!!! host=${host} port=${port}`,
    `!!! The HTTP API is now reachable from other hosts on the network.`,
    `!!! Bearer auth is MANDATORY. CORS is restricted to the configured allowlist.`,
    `!!! Token source: ${tokenSource}`,
  ];
  if (verbose) {
    lines.push(
      `!!! Token precedence: --auth-token > OPENCODE_SERVER_PASSWORD > JELLYCLAW_TOKEN > (auto, loopback only)`,
    );
  }
  lines.push(`!!! If this is unintended, stop the server (Ctrl-C) and bind to 127.0.0.1.`, rule);
  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Default async action wired for production
// ---------------------------------------------------------------------------

async function productionDeps(): Promise<ServeActionDeps> {
  const corsMod = (await import("../server/cors.js")) as {
    parseCorsOrigins: (csv: string) => readonly CorsOrigin[];
  };
  const rmMod = (await import("../server/run-manager.js")) as {
    createRunManager: (opts: {
      logger: Logger;
      paths?: SessionPaths;
      provider?: Provider;
      hooks?: HookRegistry;
      permissions?: CompiledPermissions;
      defaultModel?: string;
      defaultCwd?: string;
    }) => RunManager;
  };
  const appMod = (await import("../server/app.js")) as {
    createApp: (opts: {
      config: ServerConfig;
      runManager: RunManager;
      logger: Logger;
      configSnapshot: Record<string, unknown>;
      version: string;
    }) => Hono<{ Variables: AppVariables }>;
    createServer: (opts: {
      config: ServerConfig;
      app: Hono<{ Variables: AppVariables }>;
      logger: Logger;
      allowNonLoopback?: boolean;
    }) => Promise<{ server: HttpServer; port: number }>;
  };
  const routesMod = (await import("../server/routes/runs.js")) as {
    registerRunRoutes: (
      app: Hono<{ Variables: AppVariables }>,
      deps: {
        runManager: RunManager;
        sessionPaths: SessionPaths;
        logger: Logger;
        version: string;
      },
    ) => void;
  };

  return {
    env: process.env,
    stdout: process.stdout,
    stderr: process.stderr,
    createRunManager: ({ logger, sessionPaths }) => {
      const apiKey = process.env.ANTHROPIC_API_KEY;
      if (apiKey === undefined || apiKey.length === 0) {
        throw new AuthTokenMissingError(
          "jellyclaw serve: ANTHROPIC_API_KEY is required to run the agent loop. " +
            "Set ANTHROPIC_API_KEY in the environment before `jellyclaw serve`.",
        );
      }
      const provider = new AnthropicProvider({ apiKey, logger });
      const hooks = new HookRegistry([], { logger });
      // HTTP server is loopback + bearer-auth gated; internal tool-call
      // gating is not needed for the smoke path.
      const permissions = compilePermissions({ mode: "bypassPermissions" });
      return rmMod.createRunManager({
        logger,
        paths: sessionPaths,
        provider,
        hooks,
        permissions,
        defaultModel: DEFAULT_SERVE_MODEL,
        defaultCwd: process.cwd(),
      });
    },
    buildApp: ({ config, runManager, sessionPaths, logger, version }) => {
      const app = appMod.createApp({
        config,
        runManager,
        logger,
        configSnapshot: {},
        version,
      });
      routesMod.registerRunRoutes(app, { runManager, sessionPaths, logger, version });
      return app;
    },
    startServer: ({ config, app, logger, allowNonLoopback }) =>
      appMod.createServer({
        config,
        app,
        logger,
        ...(allowNonLoopback === true ? { allowNonLoopback: true } : {}),
      }),
    parseCorsOrigins: corsMod.parseCorsOrigins,
    onSignal: onSignalDefault,
    generateToken: () => randomBytes(32).toString("hex"),
    createLogger,
    version: "0.0.0",
  };
}

export async function serveAction(options: ServeCliOptions): Promise<number> {
  const deps = await productionDeps();
  const action = createServeAction(deps);
  return action(options);
}
