# Homebrew formula for Jellyclaw
# Generated by scripts/build-brew-formula.sh
# Do not edit directly — modify the template and regenerate.

class Jellyclaw < Formula
  desc "Open-source Claude Code replacement (wraps OpenCode)"
  homepage "https://github.com/gtrush03/jellyclaw-engine"
  url "https://example/j.dmg"
  sha256 "2baf1f40105d9501fe319a8ec463fdf4325a2a5df445adf3f572f626253678c9"
  version "0.0.1"

  depends_on :macos => :monterey

  def install
    # Extract the .app from the DMG and drop the binary into bin/.
    system "hdiutil", "attach", "-nobrowse", "-mountpoint", buildpath/"mnt", "--", cached_download
    bin.install buildpath/"mnt/Jellyclaw.app/Contents/Resources/jellyclaw-engine/jellyclaw"
    system "hdiutil", "detach", buildpath/"mnt"
  end

  test do
    assert_match "jellyclaw", shell_output("#{bin}/jellyclaw --version")
  end
end
